on:
  pull_request:
    branches: [ "main", "develop" ]
  push: 
    branches: [ "main", "develop" ]

name: Check for bloat

jobs:
  cargo_bloat:
    strategy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
