on:
  pull_request:
    branches: [ "main", "develop" ]

name: Cargo Clippy and Format
jobs:
  run_clippy_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: rustup component add clippy

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Check formatting with rustfmt
        run: cargo fmt -- --check
