name: Release on Tag Push

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build & Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add targets
        run: rustup target add "${{ matrix.target }}"

      - name: Compile binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/*
          token: ${{ secrets.GITHUB_TOKEN }}
